config_name: 'config_8'
directory: '/fast-data22/datasets/ILSVRC/2012/clsloc/'
training_folder: 'train'
test_folder: 'val_white'
img_size: [224,224]
batch_size: 32
base_learning_rate: 0.00001
sampling_rate: 0.1
target_class: 281
target_class_weight: 0.5
epochs: 5
reduceLROP_factor: 0.5
patience: 5